import {Dimensions, StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  header: {
    height: 56,
    backgroundColor: 'white',
  },
  arrow: {
    marginLeft: 19,
    marginTop: 20,
  },
  headerText: {
    fontFamily: 'TT Commons',
    fontSize: 21,
    fontWeight: 'bold',
    textAlign: 'center',
    lineHeight: 26,
    marginTop: 15,
    marginLeft: 16,
  },
  arrowHeaderText: {
    fontFamily: 'TT Commons',
    fontSize: 21,
    fontWeight: 'bold',
    textAlign: 'center',
    lineHeight: 26,
    marginTop: -21,
  },
  body: {
    backgroundColor: 'white',
    marginLeft: 12,
    marginRight: 12,
    borderTopColor: '#D7D8D9',
    borderTopWidth: 0.33,
    flex: 1,
    justifyContent: 'center',
    alignItems: 'stretch',
  },
  content: {
    backgroundColor: 'white',
    position: 'absolute',
    height: 196,
    paddingTop: 24,
    paddingBottom: 24,
    flex: 1,
    alignSelf: 'center',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'stretch',
  },
  contentText: {
    fontFamily: 'Roboto',
    fontSize: 16,
    lineHeight: 20,
    textAlign: 'center',
    width: 296,
    alignSelf: 'center',
    marginBottom: 8,
    letterSpacing: -0.32,
    color: '#818C99',
  },
  button: {
    backgroundColor: '#4986CC',
    borderRadius: 8,
    height: 36,
    width: 136,
    alignSelf: 'center',
    marginTop: 16,
  },
  optButton: {
    backgroundColor: '#F5F5F5',
    borderWidth: 0.33,
    borderStyle: 'solid',
    borderColor: 'rgba(0, 0, 0, 0.08)',
    borderRadius: 10,
    height: 62,
    marginTop: 8,
    marginBottom: 4,
    width: Dimensions.get('window').width - 24,
    alignSelf: 'center',
  },
  buttonIcon: {
    marginLeft: 14,
    marginTop: 19,
  },
  forwardIcon: {
    marginLeft: Dimensions.get('window').width - 52.25,
    marginTop: -26.25,
  },
  buttonText: {
    fontFamily: 'Roboto',
    fontSize: 16,
    lineHeight: 20,
    fontWeight: '500',
    textAlign: 'center',
    marginTop: 7.5,
    letterSpacing: 0.1,
    color: 'white',
  },
  optButtonText: {
    fontFamily: 'Roboto',
    fontSize: 16,
    lineHeight: 20,
    fontWeight: '500',
    marginTop: -31,
    marginLeft: 52,
    letterSpacing: -0.32,
    color: 'black',
  },
  optButtonNote: {
    fontFamily: 'Roboto',
    fontSize: 13,
    lineHeight: 16,
    marginLeft: 52,
    letterSpacing: -0.078,
    color: '#6D7885',
  },
  dashedBorder: {
    height: 140,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#3F8AE0',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  blueText: {
    fontFamily: 'Roboto',
    fontSize: 16,
    lineHeight: 20,
    fontWeight: '500',
    letterSpacing: -0.32,
    marginTop: 4,
    marginBottom: 4,
    marginLeft: 5,
    color: '#3F8AE0',
  },
  formText: {
    fontFamily: 'Roboto',
    marginTop: 26,
    fontSize: 14,
    lineHeight: 18,
    letterSpacing: 0.2,
    color: '#6D7885',
  },
  inputForm: {
    marginTop: 8,
    backgroundColor: '#F2F3F5',
    borderWidth: 0.5,
    borderStyle: 'solid',
    borderColor: 'rgba(0, 0, 0, 0.12)',
    borderRadius: 8,
  },
  bottomButton: {
    height: 44,
    backgroundColor: '#4986CC',
    borderRadius: 8,
    marginTop: 24,
    marginBottom: 12,
    paddingTop: 4,
  },
});

export default styles;
